# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./Source/RimsecSecurity --no-restore
    - name: Test
      run: dotnet test ./Source/RimsecSecurity --no-build --verbosity normal
      # Commits if anything new was changed
    - name: Commit
      id: commit
      run: |
          set +e
          git config --local user.name  ${{ github.actor }}        
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A .
          git commit -m "Commit updated version"
          echo "exitcode=$?" >> $GITHUB_OUTPUT
          exit "0"
      # Commits if anything new was changed
    - name: Push Changes
      uses: ad-m/github-push-action@master
      if: ${{steps.commit.outcome == success()}}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
